"""
Streamlit Utilities Package

Provides utilities for state management, caching, and file handling.
"""

from .state_manager import (
    init_session_state,
    get_workflow_step,
    set_workflow_step,
    get_project_name,
    set_project_name,
    get_uploaded_files,
    get_current_sample,
    set_current_sample,
    get_parameters,
    set_parameters,
    add_uploaded_file,
    clear_uploaded_files,
    add_processing_log,
    clear_processing_logs,
    validate_state,
    reset_session_state,
    reset_workflow,
    get_state_summary,
    is_workflow_complete,
    can_proceed_to_next_step,
)

from .cache_manager import (
    cache_image_data,
    cache_computation,
    cache_model,
    clear_all_caches,
    clear_data_cache,
    clear_resource_cache,
    get_cache_info,
    load_image_file,
    load_tiff_file,
    init_config_loader,
    cached_mask_generation,
    cached_alignment,
    cached_analysis,
    invalidate_cache_for_new_project,
    invalidate_cache_for_new_parameters,
    get_cache_performance_tips,
)

from .file_handler import (
    validate_file,
    validate_file_type,
    save_uploaded_file,
    load_file_as_bytes,
    create_download_button,
    export_to_csv,
    export_to_hdf5,
    cleanup_temp_files,
    get_temp_file_size,
    get_file_info,
    format_file_size,
    MAX_FILE_SIZE,
    ALLOWED_TYPES,
)

__all__ = [
    # State management
    "init_session_state",
    "get_workflow_step",
    "set_workflow_step",
    "get_project_name",
    "set_project_name",
    "get_uploaded_files",
    "get_current_sample",
    "set_current_sample",
    "get_parameters",
    "set_parameters",
    "add_uploaded_file",
    "clear_uploaded_files",
    "add_processing_log",
    "clear_processing_logs",
    "validate_state",
    "reset_session_state",
    "reset_workflow",
    "get_state_summary",
    "is_workflow_complete",
    "can_proceed_to_next_step",
    # Caching
    "cache_image_data",
    "cache_computation",
    "cache_model",
    "clear_all_caches",
    "clear_data_cache",
    "clear_resource_cache",
    "get_cache_info",
    "load_image_file",
    "load_tiff_file",
    "init_config_loader",
    "cached_mask_generation",
    "cached_alignment",
    "cached_analysis",
    "invalidate_cache_for_new_project",
    "invalidate_cache_for_new_parameters",
    "get_cache_performance_tips",
    # File handling
    "validate_file",
    "validate_file_type",
    "save_uploaded_file",
    "load_file_as_bytes",
    "create_download_button",
    "export_to_csv",
    "export_to_hdf5",
    "cleanup_temp_files",
    "get_temp_file_size",
    "get_file_info",
    "format_file_size",
    "MAX_FILE_SIZE",
    "ALLOWED_TYPES",
]

